spring:
    jpa:
        database: POSTGRESQL
        openInView: false
        show_sql: true
        generate-ddl: true
        hibernate:
            hbm2ddl:
                ddl-auto: "update"
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate.generate_statistics: true

    data:
       postgres:
         dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
         uri: jdbc:postgresql://earnings.csjauqzrtrfc.us-west-2.rds.amazonaws.com:5432/earnings?user=pnbmaster&password=Uts041206
         user: pnbmaster
         pass: Uts041206            